profile=gpu-hq
video-sync=display-resample
interpolation=yes
deband=yes

# Uncomment block for spdif
#audio-spdif=ac3,dts,dts-hd,eac3,truehd
#ao=alsa
#audio-exclusive=yes

alang=de,en
slang=de,en
subs-with-matching-audio=forced
subs-fallback-forced=always
hwdec=auto
volume=100
volume-max=100.0
af=scaletempo                  # Better audio pitch correction when changing speed

cache=yes
demuxer-max-bytes=1GiB

fullscreen # might cause black screen
